DROP SCHEMA IF EXISTS Ecommerce;
CREATE SCHEMA Ecommerce;

USE Ecommerce;


DROP TABLE IF EXISTS SUBSCRIPTION;
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
ID_SUBSCRIPTION INT PRIMARY KEY auto_increment,
TYPE varchar(20) NOT NULL,
DESCRIPTION varchar(99) ,
PRICE FLOAT NOT NULL,
STOCK INT NOT NULL DEFAULT 0,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE IF NOT EXISTS CATEGORY(
ID_CATEGORY INT PRIMARY KEY AUTO_INCREMENT,
CLASSIFICATION VARCHAR(30),
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS GAME;
CREATE TABLE IF NOT EXISTS GAME(
ID_GAME INT PRIMARY KEY auto_increment,
ID_CATEGORY INT NOT NULL,
NAME VARCHAR(30) NOT NULL,
DESCRIPTION varchar(100),
PRICE DECIMAL(9,2) NOT NULL,
STOCK INT NOT NULL DEFAULT 0,
RELEASE_DATE DATE NOT NULL,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);

DROP TABLE IF EXISTS USER;
CREATE TABLE IF NOT EXISTS USER (
DNI INT PRIMARY KEY NOT NULL ,
FIRTS_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
DIRECTION VARCHAR(50) NOT NULL,
BIRTH_DATE date NOT NULL,
AGE INT NOT NULL,
TELF INT NOT NULL,
MAIL VARCHAR(30) NOT NULL ,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS SHOPPING_CART;
CREATE TABLE IF NOT EXISTS SHOPPING_CART(
ID_SHOPPING_CART INT PRIMARY KEY auto_increment,
DNI INT NOT NULL,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
-- primary key(ID_SHOPPING_CART,DNI),
foreign key(DNI) REFERENCES USER(DNI)
);
 
 DROP TABLE IF EXISTS LIST_PRODUCT_CART;
CREATE TABLE IF NOT EXISTS LIST_PRODUCT_CART(
ID_LIST_PRODUCT_CART INT PRIMARY KEY AUTO_INCREMENT,
ID_GAME INT,
ID_SUBSCRIPTION INT,
ID_SHOPPING_CART INT NOT NULL,
QUANTITY INT NOT NULL,
PRICE DECIMAL(9,2) NOT NULL,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
foreign key(ID_GAME) REFERENCES GAME(ID_GAME),
foreign key(ID_SUBSCRIPTION) REFERENCES SUBSCRIPTION(ID_SUBSCRIPTION),
foreign key(ID_SHOPPING_CART) REFERENCES SHOPPING_CART(ID_SHOPPING_CART)
 );

DROP TABLE IF EXISTS BILL_PRODUCT;
CREATE TABLE IF NOT EXISTS BILL_PRODUCT(
ID_BILL INT PRIMARY KEY AUTO_INCREMENT,
DNI INT NOT NULL,
TOTAL_QUANTITY INT,
TOTAL_PRICE DECIMAL(9,2),
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
foreign key(DNI) REFERENCES USER(DNI) 
);


DROP TABLE IF EXISTS BILLING_DETAIL;
CREATE TABLE IF NOT EXISTS BILLING_DETAIL(
ID_BILLING_DETAIL INT PRIMARY KEY AUTO_INCREMENT,
ID_BILL INT NOT NULL,
ID_GAME INT,
ID_SUBSCRIPTION INT,
QUANTITY INT,
PRICE DECIMAL(9,2),
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
foreign key(ID_GAME) REFERENCES GAME(ID_GAME),
foreign key(ID_SUBSCRIPTION) REFERENCES SUBSCRIPTION(ID_SUBSCRIPTION),
foreign key(ID_BILL) REFERENCES BILL_PRODUCT(ID_BILL) 
);





